/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.shahroozsabet;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        HelloServlet classUnderTest = new HelloServlet();
    }
}
